services:
  app:
    container_name: nestjs-pokemon
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - NODE_ENV=develoment
    depends_on:
      - db
    links:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
      - ./Public:/usr/src/app/Public
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
  db:
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE=pokedex
    volumes:
      - ./mongo:/data/db
